### ISSUE TITLE
Unable to run on mac

### ISSUE THREAD

**Issue by shravanjnaidu** [moshe/elasticsearch_loader#20]
I was able to install this on a mac but I'm unable to run this on a mac. It returns the below error. Any thoughts? Is this platform dependent? Is this only tested on linux?

Traceback (most recent call last):
File "/Users/jenkins/Library/Python/3.6/bin/elasticsearch_loader", line 11, in 
load_entry_point('elasticsearch-loader==0.2.2', 'console_scripts', 'elasticsearch_loader')()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/init.py", line 565, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/init.py", line 2631, in load_entry_point
return ep.load()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/init.py", line 2291, in load
return self.resolve()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/init.py", line 2297, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/Users/jenkins/Library/Python/3.6/lib/python/site-packages/elasticsearch_loader/init.py", line 8, in 
from click_conf import conf
ModuleNotFoundError: No module named 'click_conf'

**Comment by moshe** [comment]
Actually I developed in on my mac and ran in in docker (for checking linux compatibility).
I did you installed esl?

**Comment by shravanjnaidu** [comment]
Found out the problem. I had to `pip install click_conf` and `pip install click` separately for elasticsearch_loader to work. 

Great work with the tool man! Solved my overhead like a charm!

**Comment by moshe** [comment]
Nice to hear, I will check why it happened and update the docs.
