### ISSUE TITLE
Error trying to load JSON input to ES

### ISSUE THREAD

**Issue by keremcankabadayi** [moshe/elasticsearch_loader#30]
Hey! I'm trying to load some datas to ES. When i try with POST, it adds.

```
POST titles/_doc/
{
        "CourseId":35,
        "UnitId":12390,
        "title":"Some titles",
        "id":"16069",
        "CourseName":"Some names",
        "FieldId":8,
        "field":"Some field"
  
}
```

I'm trying with this command `elasticsearch_loader --index incidents --type incident json titles.json`

I got this error

```
$ elasticsearch_loader --index incidents --type incident json titles.json 
Traceback (most recent call last):
  File "/usr/local/bin/elasticsearch_loader", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_loader/__init__.py", line 159, in main
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_loader/__init__.py", line 135, in _json
    lines = chain(*(json.load(x) for x in files))
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_loader/__init__.py", line 135, in <genexpr>
    lines = chain(*(json.load(x) for x in files))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 8 column 25 (char 222)
```

Total data is `170123`

And my `titles.json` file like

```
{...},
{...},
      {
        "CourseId":35,
        "UnitId":12390,
        "title":"xxx",
        "id":"16069",
        "CourseName":"xxx",
        "FieldId":8,
        "field":"xxx"},
      {
        "CourseId":48,
        "UnitId":396,
        "title":"xxx",
        "id":"16070",
        "CourseName":"xxx",
        "FieldId":29,
        "field":"xxx"},
{...},
{...}
```

Any help?

**Comment by keremcankabadayi** [comment]
The issue was about my file format and MY BAD.
I definitely had to read instructions carefully.

```
Commands:
  csv
  json       FILES with the format of [{"a": "1"}, {"b": "2"}]
  parquet
```
