### ISSUE TITLE
elasticsearch_loader in ubuntu: MemoryError

### ISSUE THREAD

**Issue by pythondata** [moshe/elasticsearch_loader#32]
Hi, I have the same file loaded from my mac to AWS ES, works.  But, the same code in Ubuntu got this error msg.

  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/elasticsearch_loader", line 11, in <module>
 load_entry_point('elasticsearch-loader==0.2.6', 'console_scripts', 'elasticsearch_loader')()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch_loader/__init__.py", line 160, in main
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch_loader/__init__.py", line 136, in _json
    lines = chain(*(json.load(x) for x in files))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch_loader/__init__.py", line 136, in <genexpr>
    lines = chain(*(json.load(x) for x in files))
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

**Comment by pythondata** [comment]
Hi, I have the same file loaded from my mac to AWS ES, works but same code in Ubuntu got this error msg.

**Comment by moshe** [comment]
Hey @pythondata !
Can you please comment with the arguments you supplied to `esl`?

**Comment by moshe** [comment]
Ping
