### ISSUE TITLE
jsonl not working 

### ISSUE THREAD

**Issue by danyaljj** [moshe/elasticsearch_loader#43]
I am trying to load a collection of json files. 

Here is the content of my jsonl file: 
```
{"text":"When did the Scholastic Magazine of Notre dame begin publishing?","pIdx":0,"qIdx":0}
{"text":"How often is Notre Dame's the Juggler published?","pIdx":0,"qIdx":1}
```

and here is the error I am getting: 
```
huntsman-ve500-0792:other daniel$ elasticsearch_loader --index questions --type train json squad_train_questions2.jsonl 
Traceback (most recent call last):
  File "/Users/daniel/miniconda3/bin/elasticsearch_loader", line 11, in <module>
    sys.exit(main())
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/elasticsearch_loader/__init__.py", line 160, in main
    cli()
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/elasticsearch_loader/__init__.py", line 136, in _json
    lines = chain(*(json.load(x) for x in files))
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/elasticsearch_loader/__init__.py", line 136, in <genexpr>
    lines = chain(*(json.load(x) for x in files))
  File "/Users/daniel/miniconda3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/daniel/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/daniel/miniconda3/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 94)
```

**Comment by moshe** [comment]
@danyaljj In order to load json lines you need to simply add `--json-lines` after the json commad:
`elasticsearch_loader --index questions --type train json --json-lines squad_train_questions2.jsonl `
