### ISSUE TITLE
Does not support python3

### ISSUE THREAD

**Issue by yanxurui** [Moshe/elasticsearch_loader#5]
```
Traceback (most recent call last):
  File "/usr/bin/elasticsearch_loader", line 7, in <module>
    from elasticsearch_loader import cli
  File "/usr/lib/python3.5/site-packages/elasticsearch_loader.py", line 7, in <module>
    from click_stream import Stream
  File "/usr/lib/python3.5/site-packages/click_stream.py", line 3, in <module>
    from urlparse import urlparse
ImportError: No module named 'urlparse'
```

**Comment by Moshe** [comment]
Fixed import errors, give it a try (:
